version: '3.8'
services:
  kpi-ui-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_API_URL=${REACT_APP_BACKEND_API_URL}
      - REACT_APP_JWT_TOKEN=${REACT_APP_JWT_TOKEN}
    env_file:
      - .env 